### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by poustmal** [ArufaTeam/Arufa#11]
Is this another tesseract respitory that will be deleted or a new software that will stay here?

**Comment by Lazerplayz** [comment]
No @AppleDevelops will continue to work on this software and this is no were near the same as tesseract.

**Comment by TheRoyalBlock** [comment]
This is completely different from Tesseract, and this will stay here.

**Comment by NFGamerMC** [comment]
This will not be deleted and we recommend switching to this.
